import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  let books = ["hi", "hello", "annyong"];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="text-red-300 space-x-11 flex">
        {books.map((e) => (
          <div className="">{e}</div>
        ))}
      </div>
    </div>
  );
}
